// USER REDUCER ACTIONS
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const UPDATE_USER = 'UPDATE_USER';

// LOOKUPS REDUCER ACTIONS
export const SET_LOOKUPS = 'SET_LOOKUPS';
export const CLEAR_LOOKUPS = 'CLEAR_LOOKUPS';

// MODALS REDUCER ACTIONS
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

// SETTINGS REDUCER ACTIONS
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const SET_LOADING = 'SET_LOADING';
export const SET_MENU = 'SET_MENU';

// JOB REDUCER ACTIONS
export const SET_JOB = 'SET_JOB';
export const CLEAR_JOB = 'CLEAR_JOB';

// JOBS REDUCER ACTIONS
export const SET_JOBS = 'SET_JOBS';
export const CLEAR_JOBS = 'CLEAR_JOBS';

// JOB DEFINITION REDUCER ACTIONS
export const SET_JOB_DEFINITION = 'SET_JOB_DEFINITION';
export const CLEAR_JOB_DEFINITION = 'CLEAR_JOB_DEFINITION';

// JOBS DEFINITIONS REDUCER ACTIONS
export const SET_JOB_DEFINITIONS = 'SET_JOB_DEFINITIONS';
export const CLEAR_JOB_DEFINITIONS = 'CLEAR_JOB_DEFINITIONS';

// BATCH REDUCER ACTIONS
export const SET_BATCH = 'SET_BATCH';
export const CLEAR_BATCH = 'CLEAR_BATCH';

// BATCHES REDUCER ACTIONS
export const SET_BATCHES = 'SET_BATCHES';
export const CLEAR_BATCHES = 'CLEAR_BATCHES';
export const SET_BATCH_DEFINITIONS = 'SET_BATCH_DEFINITIONS';
export const CLEAR_BATCH_DEFINITIONS = 'CLEAR_BATCH_DEFINITIONS';

// CONTAINER REDUCER ACTIONS
export const SET_CONTAINER = 'SET_CONTAINER';
export const CLEAR_CONTAINER = 'CLEAR_CONTAINER';

// PARAMETERS REDUCER ACTIONS
export const SET_PARAMETERS = 'SET_PARAMETERS';
export const CLEAR_PARAMETERS = 'CLEAR_PARAMETERS';

export const SET_PROJECTS = 'SET_PROJECTS';
export const CLEAR_PROJECTS = 'CLEAR_PROJECTS';
export const CLEAR_PROJECT = 'CLEAR_PROJECT';
export const SET_PROJECT = 'SET_PROJECT';
export const SHOW_ALERT = 'SHOW_ALERT';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const SET_CURRENT_JOB = 'SET_CURRENT_JOB';
export const SET_CURRENT_JOBS = 'SET_CURRENT_JOBS';
export const SAVE_DEFINITION = 'SAVE_DEFINITION';
export const DEFINITION_CHANGED = 'DEFINITION_CHANGED';
export const SET_CURRENT_DEFINITIONS = 'SET_CURRENT_DEFINITIONS';
export const EDIT_BATCH_ROW = 'EDIT_BATCH_ROW';
